theme: jekyll-theme-architect
title: Cristhian Mayuri
description: Web-blog perteniciente a Cristhian Mayuri
show_downloads: false
github:
  zip_url: http://example.com/download.zip
  tar_url: http://example.com/download.tar